channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bamtools
  - bioconductor-gviz
  - bioconductor-rtracklayer
  - cyvcf2
  - d4tools
  - hypothesis
  - jupyter
  - msprime
  - ncbi-datasets-cli
  - nodejs
  - notebook
  - numpy=1.26.2
  - pandas
  - pip
  - plotly
  - pybedtools
  - pyfaidx
  - pympler
  - pyranges
  - pytest
  - pytest-cov
  - pytest-runner
  - python=3.11
  - python-dotenv
  - r-circlize
  - r-codetools
  - r-devtools
  - r-dotenv
  - r-dplyr
  - r-ggplot2
  - r-gviz
  - r-kableExtra
  - r-viridis
  - r-tidyr
  - samtools
  - scikit-allel
  - seaborn
  - seqkit
  - snakemake
  - tqdm
  - pip:
      - cite2c
      - pixy
      - pre_commit
      - pyd4
      - pyfastx
      - sgkit[vcf]
      # Fixes numpy 1.24 issue (cf issue #1079 )
      - "--editable=git+https://github.com/pystatgen/sgkit.git@298fbbc7e2c5673880a0d4075d32668d338249db"
